apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.dbService.name }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: {{ .Values.dbService.port }}
  selector:
    {{- include "petclinic.dbselectorLabels" . | nindent 4 }}
