apiVersion: v1
kind: Service
metadata:
  name: {{ include "petclinic.name" . }} #fullname
  labels:
    {{- include "petclinic.labels" . | nindent 4 }}
  namespace: {{ .Values.namespace}}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.targetPort }}
  selector:
    {{- include "petclinic.selectorLabels" . | nindent 4 }}
